theme: minima
title: Your Awesome HPC Blog
author: Albert Reuther
email: reuther@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Just a practice blog post.

# social links
twitter_username: areuther1 # DO NOT include the @ character, or else the build will fail!
github_username:  areuther # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
